// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoFinal.Data;

#nullable disable

namespace ProjetoFinal.Migrations
{
    [DbContext(typeof(GinasioDbContext))]
    [Migration("20260209124157_Add room to ScheduleClass")]
    partial class AddroomtoScheduleClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoFinal.Models.Aula", b =>
                {
                    b.Property<int>("IdAula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAula"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdAula");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("aulas", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.AulaMarcada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAula")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAula")
                        .HasColumnType("int");

                    b.Property<int>("Sala")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAula");

                    b.ToTable("aulas_marcadas", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.AvaliacaoFisica", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("IdMembro")
                        .HasColumnType("int");

                    b.Property<decimal>("Imc")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("MassaGorda")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MassaMuscular")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("IdFuncionario");

                    b.HasIndex("IdMembro");

                    b.ToTable("avaliacoes_fisicas", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.Exercicio", b =>
                {
                    b.Property<int>("IdExercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_exercicio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExercicio"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdExercicio");

                    b.ToTable("exercicios", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_funcionario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.Membro", b =>
                {
                    b.Property<int>("IdMembro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_membro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMembro"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("date");

                    b.Property<int?>("IdPlanoTreino")
                        .HasColumnType("int");

                    b.Property<int>("IdSubscricao")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMembro");

                    b.HasIndex("IdPlanoTreino");

                    b.HasIndex("IdSubscricao");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("membros", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.MembroAula", b =>
                {
                    b.Property<int>("IdMembro")
                        .HasColumnType("int");

                    b.Property<int>("IdAulaMarcada")
                        .HasColumnType("int");

                    b.Property<int?>("AulaIdAula")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("date");

                    b.Property<string>("Presenca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMembro", "IdAulaMarcada");

                    b.HasIndex("AulaIdAula");

                    b.HasIndex("IdAulaMarcada");

                    b.HasIndex("IdMembro", "IdAulaMarcada")
                        .IsUnique();

                    b.ToTable("membros_aulas", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.MembroAvaliacao", b =>
                {
                    b.Property<int>("IdMembroAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMembroAvaliacao"));

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdAvaliacaoFisica")
                        .HasColumnType("int");

                    b.Property<int>("IdMembro")
                        .HasColumnType("int");

                    b.HasKey("IdMembroAvaliacao");

                    b.HasIndex("IdAvaliacaoFisica")
                        .IsUnique()
                        .HasFilter("[IdAvaliacaoFisica] IS NOT NULL");

                    b.HasIndex("IdMembro");

                    b.ToTable("membros_avaliacoes", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.Pagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPagamento"));

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataRegisto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EstadoPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdMembro")
                        .HasColumnType("int");

                    b.Property<int>("IdSubscricao")
                        .HasColumnType("int");

                    b.Property<DateTime>("MesReferente")
                        .HasColumnType("date");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPagamento");

                    b.HasIndex("IdMembro");

                    b.HasIndex("IdSubscricao");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.PlanoExercicio", b =>
                {
                    b.Property<int>("IdPlano")
                        .HasColumnType("int");

                    b.Property<int>("IdExercicio")
                        .HasColumnType("int");

                    b.Property<decimal>("Carga")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("IdPlano", "IdExercicio");

                    b.HasIndex("IdExercicio");

                    b.ToTable("planos_exercicios", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.PlanoTreino", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_plano");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlano"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.HasKey("IdPlano");

                    b.HasIndex("IdFuncionario");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("planos_treino", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.RefreshToken", b =>
                {
                    b.Property<int>("IdRefresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_refresh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRefresh"));

                    b.Property<bool>("Cancelado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("SubstituidoPor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("datetime2");

                    b.HasKey("IdRefresh");

                    b.HasIndex("IdUser", "Token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.Subscricao", b =>
                {
                    b.Property<int>("IdSubscricao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_subscricao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubscricao"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdSubscricao");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("subscricoes", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("PrimeiraVez")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Ativo] = 1");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProjetoFinal.Models.Aula", b =>
                {
                    b.HasOne("ProjetoFinal.Models.Funcionario", "Funcionario")
                        .WithMany("Aulas")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("ProjetoFinal.Models.AulaMarcada", b =>
                {
                    b.HasOne("ProjetoFinal.Models.Aula", "Aula")
                        .WithMany("AulasMarcadas")
                        .HasForeignKey("IdAula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("ProjetoFinal.Models.AvaliacaoFisica", b =>
                {
                    b.HasOne("ProjetoFinal.Models.Funcionario", "Funcionario")
                        .WithMany("AvaliacoesFisicas")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoFinal.Models.Membro", "Membro")
                        .WithMany("AvaliacoesFisicas")
                        .HasForeignKey("IdMembro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Funcionario", b =>
                {
                    b.HasOne("ProjetoFinal.Models.User", "User")
                        .WithOne("Funcionario")
                        .HasForeignKey("ProjetoFinal.Models.Funcionario", "IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Membro", b =>
                {
                    b.HasOne("ProjetoFinal.Models.PlanoTreino", "PlanoTreino")
                        .WithMany()
                        .HasForeignKey("IdPlanoTreino")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjetoFinal.Models.Subscricao", "Subscricao")
                        .WithMany("Membros")
                        .HasForeignKey("IdSubscricao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoFinal.Models.User", "User")
                        .WithOne("Membro")
                        .HasForeignKey("ProjetoFinal.Models.Membro", "IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanoTreino");

                    b.Navigation("Subscricao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetoFinal.Models.MembroAula", b =>
                {
                    b.HasOne("ProjetoFinal.Models.Aula", null)
                        .WithMany("MembrosAulas")
                        .HasForeignKey("AulaIdAula");

                    b.HasOne("ProjetoFinal.Models.AulaMarcada", "AulaMarcada")
                        .WithMany("MembrosAulas")
                        .HasForeignKey("IdAulaMarcada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoFinal.Models.Membro", "Membro")
                        .WithMany("MembroAulas")
                        .HasForeignKey("IdMembro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AulaMarcada");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("ProjetoFinal.Models.MembroAvaliacao", b =>
                {
                    b.HasOne("ProjetoFinal.Models.AvaliacaoFisica", "AvaliacaoFisica")
                        .WithOne()
                        .HasForeignKey("ProjetoFinal.Models.MembroAvaliacao", "IdAvaliacaoFisica")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjetoFinal.Models.Membro", "Membro")
                        .WithMany("MembroAvaliacoes")
                        .HasForeignKey("IdMembro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvaliacaoFisica");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Pagamento", b =>
                {
                    b.HasOne("ProjetoFinal.Models.Membro", "Membro")
                        .WithMany("Pagamentos")
                        .HasForeignKey("IdMembro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoFinal.Models.Subscricao", "Subscricao")
                        .WithMany("Pagamentos")
                        .HasForeignKey("IdSubscricao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membro");

                    b.Navigation("Subscricao");
                });

            modelBuilder.Entity("ProjetoFinal.Models.PlanoExercicio", b =>
                {
                    b.HasOne("ProjetoFinal.Models.Exercicio", "Exercicio")
                        .WithMany("PlanosExercicios")
                        .HasForeignKey("IdExercicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlanosExercicios_Exercicio");

                    b.HasOne("ProjetoFinal.Models.PlanoTreino", "PlanoTreino")
                        .WithMany("PlanosExercicios")
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlanosExercicios_PlanoTreino");

                    b.Navigation("Exercicio");

                    b.Navigation("PlanoTreino");
                });

            modelBuilder.Entity("ProjetoFinal.Models.PlanoTreino", b =>
                {
                    b.HasOne("ProjetoFinal.Models.Funcionario", "Funcionario")
                        .WithMany("PlanosTreino")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("ProjetoFinal.Models.RefreshToken", b =>
                {
                    b.HasOne("ProjetoFinal.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Aula", b =>
                {
                    b.Navigation("AulasMarcadas");

                    b.Navigation("MembrosAulas");
                });

            modelBuilder.Entity("ProjetoFinal.Models.AulaMarcada", b =>
                {
                    b.Navigation("MembrosAulas");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Exercicio", b =>
                {
                    b.Navigation("PlanosExercicios");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Funcionario", b =>
                {
                    b.Navigation("Aulas");

                    b.Navigation("AvaliacoesFisicas");

                    b.Navigation("PlanosTreino");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Membro", b =>
                {
                    b.Navigation("AvaliacoesFisicas");

                    b.Navigation("MembroAulas");

                    b.Navigation("MembroAvaliacoes");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("ProjetoFinal.Models.PlanoTreino", b =>
                {
                    b.Navigation("PlanosExercicios");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Subscricao", b =>
                {
                    b.Navigation("Membros");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("ProjetoFinal.Models.User", b =>
                {
                    b.Navigation("Funcionario");

                    b.Navigation("Membro");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
